name: finance-demo-project
description: ''
version: '1.1'
author: shubhang3000@outlook.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: financedemoproject
  parentArtefactID: financeteam
  buildSystem: wheel
  author: null
  createdAt: '2023-11-01 08:58:52'
pipelines:
  pipelines/finance-demo-pipeline:
    name: finance-demo-pipeline
    description: ''
    author: shubhang3000@outlook.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-11-01 08:58:52'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs:
  jobs/finance_job:
    name: finance_job
    description: ''
    fabricUID: 6535
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: finance-job-size
    scheduleCron: 0 0 14 * * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/finance-demo-pipeline
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2023-11-03 08:08:48'
    author: shubhang3000@outlook.com
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
functions:
  author: null
  createdAt: '2023-11-01 08:58:52'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2023-11-01 08:58:32'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-11-01 08:58:32'
pipelineConfigurations: {}
